on:
  workflow_dispatch:

jobs:
  build:
    name: build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
      - name: npm install and build
        run: |
          npm install --production
          npm run package
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: app-${{ runner.os }}
          path: out/make/*
  release:
    name: release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          prerelease: true
          files: out/make/*
